version: '3'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: api-service
    restart: unless-stopped
    environment:
      - NODE_ENV=$NODE_ENV
      - LOG_LEVEL=$LOG_LEVEL

      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB_NAME=$POSTGRES_DB_NAME
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/home/app
    networks:
      - app-network
    depends_on:
      - "postgres-db"
    command: ["./wait-for-service-start.sh", "postgres-db:5432", "--", "npm", "run", "dev"]

  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
