export const INTERNAL_FAILURE = 'ERR_INTERNAL_FAILURE';
export const BAD_REQUEST = 'ERR_BAD_REQUEST';
export const UNAUTHORISED = 'ERR_UNAUTHORISED';
export const FORBIDDEN = 'ERR_FORBIDDEN';
export const NOT_FOUND = 'ERR_NOT_FOUND';
export const CONFLICT = 'ERR_CONFLICT';
export const CLIENT_TYPE_NOT_SUPPORTED = 'ERR_CLIENT_TYPE_NOT_SUPPORTED';
export const EVENT_HANDLER_NOT_FOUND = 'ERR_EVENT_HANDLER_NOT_FOUND';
export const REQUEST_TIMED_OUT = 'ERR_REQUEST_TIMED_OUT';
export const PROCESSING_FAILED = 'ERR_PROCESSING_FAILED';

export default {
  INTERNAL_FAILURE,
  BAD_REQUEST,
  UNAUTHORISED,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT,
  PROCESSING_FAILED,
  CLIENT_TYPE_NOT_SUPPORTED,
  EVENT_HANDLER_NOT_FOUND,
  REQUEST_TIMED_OUT
};

